### ISSUE TITLE
403 trying to access any account?

### ISSUE THREAD

**Issue by g12mcgov** [plaid/quickstart#13]
Hi There,

I followed the quickstart guide for Python & Node, and when I try and run the local server and log into any of my accounts, I'm getting a 403 on the underlying request.

Am I naive, or should I be able to simple use my existing BofA login, for instance, and be able to successfully log in?

![screenshot 2017-08-02 21 47 09](https://user-images.githubusercontent.com/4671394/28902366-743e7212-77cc-11e7-9f4b-3343b7939682.png)

![screenshot 2017-08-02 21 50 28](https://user-images.githubusercontent.com/4671394/28902384-9c75b024-77cc-11e7-96be-64610248782b.png)

I should mention I'm using sandbox, would that have an effect?

**Comment by nathankot** [comment]
Hey @g12mcgov! The sandbox environment doesn't actually accept real credentials, there's a hardcoded set of [sandbox credentials](https://plaid.com/docs/api/#creating-items-in-the-sandbox) that you need to use instead 😄

**Comment by g12mcgov** [comment]
Hmm @nathankot I tried those, and still no luck -- same issue as above.  Isn't that kind of futile anyways if I want to get real access to my accounts? I'm guessing real access is only available to production accounts :disappointed:

**Comment by nathankot** [comment]
@g12mcgov

We have a [`development` environment](https://plaid.com/docs/api/#introduction) which gives you access to an upper limit of account adds. You need to first file a request for that environment through our [dashboard](https://dashboard.plaid.com)

What are the sandbox credentials that you are using? Could you post your `Plaid.create` call here?

 The `/authenticate` call in your screenshot looks a little suspect to me - it shouldn't be hitting `cdn.plaid.com`. It also indicates to me that you might be using api-v1 which would explain the sandbox credentials not working - since those are specific to api-v2. Could you try removing `apiVersion` or setting it to `v2`?
