### ISSUE TITLE
Python quickstart example fails

### ISSUE THREAD

**Issue by skorokithakis** [plaid/quickstart#133]
The Python quickstart example JS code fails with:

```
Uncaught Error: Missing Link parameter. Link requires a key or token to be provided.
```

**Comment by vinnyoodles** [comment]
I'm getting this error with the quickstart example.

```Error Message: secret must be a properly formatted, non-empty string```

**Comment by phoenixy1** [comment]
See https://stackoverflow.com/questions/63287664/plaid-cant-run-python-quickstart for a similar issue, which was user error combined with terrible error messaging.  We fixed this by fixing the error messaging so that developers can more effectively troubleshoot it.  @skorokithakis are you still having this problem with the latest version of the Quickstart?

**Comment by otherchen** [comment]
Hi @skorokithakis, thank you for creating this issue! Because of inactivity on this issue and because it seems similar to an issue we already addressed, I am going to close this out for now. 

If what @phoenixy1 posted above does not work for you, feel free to reopen!
