### ISSUE TITLE
link-initialize.js:1 Uncaught Error: Missing Link parameter. Link requires a key or token to be provided.

### ISSUE THREAD

**Issue by mrcartier** [plaid/quickstart#134]
Trying to run the python quickstart. Currently I have the following in server.py

PLAID_CLIENT_ID = '123XXXXXXXX123' 
PLAID_SECRET = '321XXXXX321'
PLAID_ENV = 'sandbox' 
PLAID_PRODUCTS = 'transactions' 
PLAID_COUNTRY_CODES = 'US'

When I run server.py & check in the browser the Connect with Plaid button can't be selected & the list of banks never populate - it just seems to be repeatedly loading...

When I check index.html using dev tools I get the message "Uncaught Error: Missing Link parameter. Link requires a key or token to be provided." (see screenshot below).

![Screenshot_2020-08-06_00-53-10](https://user-images.githubusercontent.com/6580221/89492321-57147b80-d77f-11ea-9c68-c38b8428eeab.png)

Has anyone experienced this issue or know why it occurs? As best I can tell I've followed the quickstart instructions by entering client_id, secret & other variables...

**Comment by otherchen** [comment]
Hey @mrcartier! Thanks for surfacing this issue.

I just tried:

1. Pulling the latest master

2. Running the following:
```
PLAID_CLIENT_ID='MY_CLIENT_ID' \
PLAID_SECRET='MY_SANDBOX_SECRET' \
PLAID_ENV='sandbox' \
PLAID_PRODUCTS='transactions' \
PLAID_COUNTRY_CODES='US' \
python server.py
```

3. Visiting `http://localhost:8000/`

4. Clicking `Connect with Plaid`

And it works for me 🤔 

The error message that you posted above indicates that there may be an issue with creating a `link_token`. This _may_ be because your client_id and secret are invalid. Do you mind pulling from latest master and retrying with the client_id and sandbox secret from your Plaid dashboard?

**Comment by otherchen** [comment]
Hey @mrcartier, are you using a `PLAID_REDIRECT_URI` per chance? If so, you'll need to register the uri in the Plaid Dashboard.

I've also merged https://github.com/plaid/quickstart/pull/136 which surfaces errors with link_token creation so if you pull latest master and try again, you may get more information as to why the quickstart is failing.

**Comment by mrcartier** [comment]
Thanks for getting back to me @otherchen. I used the updated index.html file & the errors were visible. Country codes and products need to be listed as string arrays so I just added [ and ].
