### ISSUE TITLE
NestJS

### ISSUE THREAD

**Issue by shammy8** [plaid/quickstart#210]
Sorry if this isn't the right place to ask this. But  any plans of creating an example with NestJs instead of Express?

**Comment by phoenixy1** [comment]
No worries, this is a great place to ask this!

We don't currently have any plans to do a NestJS Quickstart, but we'll definitely track the request!  This kind of feedback is super helpful as we're always trying to make sure that the platforms we offer for the Quickstart match what folks want to use.  (Which is why we recently switched it from vanilla JavaScript + jQuery to React.). If your friends want to use NestJs with Plaid too, make sure they open tickets as well so we can get a sense of the demand :-).

That said, the actual Express here is nothing fancy and hopefully it is not too hard to implement what you're looking to do in NestJs -- if you have any questions or run into a problem, don't hesitate to open a ticket here or post on Stack Overflow.

(Let me know if this answers your question!  If it does, I'll go ahead and close the issue.)

**Comment by phoenixy1** [comment]
closing since I haven't heard back -- feel free to create a new issue if necessary!
