### ISSUE TITLE
No license on the quickstart project?

### ISSUE THREAD

**Issue by greg-dryke** [plaid/quickstart#260]
I was hoping to leverage the quickstart project as a base for a project, reusing the boilerplate code.

However, I'm not seeing a license on the repo, and nothing turned up in a couple quick searches. Is there a statement about the license that this repo is covered under?

It looks like the libraries themselves are MIT?

**Comment by phoenixy1** [comment]
Hah -- honestly I bet the issue is just that the Quickstart was originaly created so long ago that nobody was thinking about licensing back then. I'm checking with our legal team to be sure but I assume we will put the MIT license on it. And I promise I won't get mad if you re-use some of the Quickstart code for your project :-).

**Comment by greg-dryke** [comment]
That's what I assumed 😁  thank you for checking!
