### ISSUE TITLE
python container starts in the wrong context

### ISSUE THREAD

**Issue by masinusa** [plaid/quickstart#373]
When I clone and run 'make up language=python', the build breaks because the dockerfile is being built in the quickstart/ context, instead of the quickstart/python context -- so there is no requirements.txt file.

**Comment by phoenixy1** [comment]
@lindawoo-plaid or @ToddKerpelman would one of you mind looking into this? I can't run the Dockerized quickstart at all (some kind of dependency issue involving fsevents) so it's a bit tough for me to troubleshoot

**Comment by lindawoo-plaid** [comment]
Todd, Do you have time to take this on?  I am a bit swamped right now...

**Comment by phoenixy1** [comment]
@masinusa thank you for the report! Are you blocked on this? We will definitely investigate as soon as we can, but our team staffing is a little low this week due to scheduled PTO and fintech_devcon, so it might not be until next week if that's OK.

**Comment by mschmidt271** [comment]
The problem is #364. There's a comment on the [commit](https://github.com/plaid/quickstart/commit/f5eeac6f656303ff18efacb82cb1a66288c95f1c) (not the PR) questioning the reasoning. As far as I can tell it just deletes a necessary line--maybe intended as a fix on a different branch? Or different os/docker? I'm on Monterey/Docker v20.10.17, if that helps, and if I add the line back in the build succeeds. Although, fwiw, I'm brand new to Plaid.
