### ISSUE TITLE
payment_initiation doesn't work

### ISSUE THREAD

**Issue by mswoff** [plaid/quickstart#437]
It seems like all the code is setup to support the `payment_initiation` product, but once it's specified as part of `PLAID_PRODUCTS`, everything breaks and you can't select an institution (They all say connectivity not supported).

I separately tried to add `transfer` to `PLAID_PRODUCTS`, and the frontend isn't setup for that.

**Comment by phoenixy1** [comment]
@mswoff are you sure you're combining payment initiation with a supported configuration? In particular, payment initiation only works in europe/uk, so if you set products to `payment_initiation` but leave the country code as the default `US,CA` then you'll get the behavior you're describing because no US or CA institutions support payment initiation.

I'm not sure what you mean by the frontend not being set up for transfer -- there are some endpoints to test transfer calls. Specifically, the way the quickstart works is that initializing with transfer will cause a transfer to automatically be initiated; you can then get its details via calling `/transfer/get`.

**Comment by phoenixy1** [comment]
Closing this issue as it seems likely to be user error rather than a bug in the quickstart, but feel free to comment to follow up if this did not resolve the problem.
