### ISSUE TITLE
Getting the Link Token using create link token but the button to link bank account is disabled !

### ISSUE THREAD

**Issue by sarthak-arora1997** [plaid/quickstart#459]
I am trying to integrate Plaid Auth in a pre existing website for my employer and it has been a very tiresome and painful process to get to this point as I am very new to both ReactJS and NodeJS. Any form of help with this would be highly appreciated !!!

Below I have defined the Button which when clicked should allow me to LinkAccounts, but not able to click the button even though the ready variable = True and the console shows a valid Link Token in the sandbox ENV as well.
<img width="582" alt="Screenshot 2024-01-09 at 7 52 00 PM" src="https://github.com/plaid/quickstart/assets/89552757/a515ab6f-91ee-4b87-9951-fdd210c3d149">

The below 2 snapshots are from App.js file in my frontend where I am getting the Link token from my backend and passing it as a prop to the Link function seen in the above snapshot
<img width="711" alt="Screenshot 2024-01-09 at 7 53 07 PM" src="https://github.com/plaid/quickstart/assets/89552757/d09c8ce8-3fb4-4465-b583-974b709b1d30">
<img width="966" alt="Screenshot 2024-01-09 at 7 57 17 PM" src="https://github.com/plaid/quickstart/assets/89552757/1f2c3c87-5ed6-487e-afd5-0cb916617494">

**Comment by phoenixy1** [comment]
If you've confirmed that Ready is True but the button still has the disabled state, then it seems like the issue is unrelated to Plaid.

As a starting place, I'd suggest looking at the sample frontend code in the Quickstart or [Tiny Quickstart](https://github.com/plaid/tiny-quickstart/blob/main/react/src/App.jsx) and modifying it to meet your needs, as that code is verified to work. 

Closing this issue at this point as it is not reporting an issue with the Quickstart. If you need additional help, feel free to contact Support.

**Comment by sarthak-arora1997** [comment]
@phoenixy1 pasting the console log output below:
<img width="700" alt="Screenshot 2024-01-10 at 12 47 25 PM" src="https://github.com/plaid/quickstart/assets/89552757/21b88e9e-94f8-42c2-bcc2-f21bf638f398">
as you can see in the above ready is false initially and is set to true later, would that have any impact on the button not being clickable ?

**Comment by phoenixy1** [comment]
@sarthak-arora1997 Hmm, it seems like is really a React question rather than a Plaid question -- if you're still having trouble, I'd recommend you try on more React-based forums or general programming forums (like Stack Overflow with the React tag).
