### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by reidprichard** [plaid/quickstart#496]
I've tried launching on 3 machines, with and without Docker, on Windows and Linux, with NPM and Python, and in all cases I get "Cannot GET /" when visiting localhost:8000. I even tried rolling back to a commit from June with the same result.

**Comment by phoenixy1** [comment]
This is expected behavior; the quickstart backend runs on port 8000, and the frontend runs on port 3000. Make sure you are starting the frontend as described here: https://github.com/plaid/quickstart/?tab=readme-ov-file#2-running-the-frontend

Normally when you start the frontend, it will automatically open a browser session on localhost:3000, but if it doesn't, you can always go there manually after launching the frontend.
